name: NISTKAT OV256_244_96_pkc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    name: Ubuntu ${{ matrix.impl }} ${{ matrix.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc:
          - gcc
          - clang
        impl:
          - ref
          - avx2
          - ssse3
          - amd64
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make KAT=1 PARAM=5 VARIANT=2 PROJ=${{ matrix.impl }} check-NISTKAT
      env:
        CC: ${{ matrix.cc }}
  test-macos:
    name: MacOS ${{ matrix.impl }} ${{ matrix.cc }}
    strategy:
      matrix:
        cc:
          - clang
          - gcc-12
        impl:
          - ref
          - ssse3
          - amd64
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Set up compiler
      run: 'export CC=${{ matrix.cc }}'
    - name: test
      run: |
        function sha256sum() { shasum -a 256 "$@" ; } && export -f sha256sum
        make KAT=1 PARAM=5 VARIANT=2 PROJ=${{ matrix.impl }} check-NISTKAT
      env:
        CC: ${{ matrix.cc }}
        LDFLAGS: "-L/usr/local/opt/openssl@3/lib"
        CFLAGS: "-I/usr/local/opt/openssl@3/include"
