name: Test OV16_160_64_classic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc:
          - gcc
          - clang
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make PARAM=1 VARIANT=1 test
      env:
        CC: ${{ matrix.cc }}
