name: Test OV256_244_96_classic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: ${{ matrix.impl }} ${{ matrix.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc:
          - gcc
          - clang
        impl:
          - ref
          - avx2
          - ssse3
          - amd64
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} test
      env:
        CC: ${{ matrix.cc }}
    - name: asan
      run: |
        make clean
        make ASAN=1 PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} test
      env:
        CC: ${{ matrix.cc }}
    - name: ubsan
      run: |
        make clean
        make UBSAN=1 PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} test
      env:
        CC: ${{ matrix.cc }}
  valgrind:
    name: Valgrind constant-time check ${{ matrix.impl }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        impl:
          - ref
          - avx2
          - ssse3
          - amd64
    steps:
    - uses: actions/checkout@v3
    - name: Install Valgrind
      run: sudo apt install valgrind
    - name: valgrind
      run: |
        make VALGRIND=1 PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} sign_api-test
        valgrind --error-exitcode=1 --exit-on-first-error=yes --leak-check=yes ./sign_api-test
  test-macos:
    strategy:
      matrix:
        compiler:
          - clang  # XCode (Apple LLVM/Clang)
          - gcc   # GNU (Homebrew)
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
      - name: Set up GCC compiler
        run: 'export PATH="/usr/local/bin:$PATH" && export CC=gcc'
        if: matrix.compiler == 'gcc'
    - name: test
      run: make PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} test
      env:
        CC: ${{ matrix.cc }}
    - name: asan
      run: |
        make clean
        make ASAN=1 PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} test
      env:
        CC: ${{ matrix.cc }}
    - name: ubsan
      run: |
        make clean
        make UBSAN=1 PARAM=5 VARIANT=1 PROJ=${{ matrix.impl }} test
      env:
        CC: ${{ matrix.cc }}

