name: Test OV256_184_72_classic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc:
          - gcc
          - clang
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make PARAM=4 VARIANT=1 test
      env:
        CC: ${{ matrix.cc }}
    - name: asan
      run: |
        make clean
        make ASAN=1 PARAM=4 VARIANT=1 test
      env:
        CC: ${{ matrix.cc }}
    - name: ubsan
      run: |
        make clean
        make UBSAN=1 PARAM=4 VARIANT=1 test
      env:
        CC: ${{ matrix.cc }}
