name: Test OV256_96_64_pkc_skc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}.${{ matrix.compiler.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc:
          - gcc
          - clang
    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make PARAM=2 VARIANT=3 test
